### PR TITLE
Revert breaking change

### PR DESCRIPTION
**Pull request by oxinabox**
Reverts #31 and #28 and bumps the patch version.
Turns out they were not non-breaking changes as they changed the behavour of `load` which is part of the API

I have confirmed on two internal packages that use JLSO that this branch makes them work again.

This PR will be followed by another PR which will revert *this* PR, and bumping the version to `v2.0.0-DEV` bring us back to where we are now, minus lying about semver.

From there we can decide:
 -  if we want to release `v2.0.0`
 -  or if we can workout how to do this in a nonbreaking way, and so can do that and then tag `v1.2.2`.
 - or we might want to sit on `v2.0.0-DEV` and bring in a bunch of other breaking changes.

### CODE REVIEW

**Comment by rofinn** [comment]
Fair enough. I also noticed that batch updating of JLSO files is actually a little annoying on 1.2  #34 , so we might want to address that pain point before we release 2.0. Alternatively, we could revert just the breaking change by having `JLSO.load` and return `Dict{String, Any}`? My concern with just releasing 2.0 is that we'll want to drop the deprecations, but then they won't have had a full cycle to notify people of the upcoming changes.

**Comment by oxinabox** [comment]
Those are options for what to do before releasing what ever the release after this is,
be it `1.2.2` or `2.0.0`

**Comment by oxinabox** [comment]
@rofinn  did you review and approve this?

**Comment by rofinn** [comment]
I'll note that releasing this revert may be more breaking for anyone who has made a JLSO file since 1.2 was released.

**Comment by oxinabox** [comment]
> I'll note that releasing this revert may be more breaking for anyone who has made a JLSO file since 1.2 was released.

And that is why it is unfortunate that we did not revert this 6 days ago when it was discovered.
Never-the-less, this is the correct action to take by semver.

**Pull request merged**
