### PR TITLE
Bump minor version

### PR DESCRIPTION
**Pull request by nickrobinson251**
Can we release a version with #28 please?

### CODE REVIEW

**Comment by rofinn** [comment]
#29 Should be addressed before we release a new version. There's also this issue that I'm not sure how best to address https://github.com/invenia/JLSO.jl/pull/28#issuecomment-543948907

**Comment by nickrobinson251** [comment]
> #29 Should be addressed before we release a new version. 

ahha, good point!

> There's also this issue that I'm not sure how best to address [#28 (comment)](https://github.com/invenia/JLSO.jl/pull/28#issuecomment-543948907)

I'm not sure this one is blocking for tagging a new version (but yes, would be nice to think up something here)

**Comment by rofinn** [comment]
If you rebase with master this should pass tests and be good to go

**Comment by nickrobinson251** [comment]
Thanks, Rory! :) I'd missed your comment.

**Pull request merged**
