### PR TITLE
Extend [compat] CodecZlib = "0.6, 0.7"

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by oxinabox** [comment]
Thanks for this,
I just checked and there was no actual breaking change between 0.6 and 0.7 of CodecZlib. :-(

**Comment by oxinabox** [comment]
Can you bump the version of JLSO in the Project.toml to 2.3.0 ?
Then can merge this and tag a release.

**Comment by ablaom** [comment]
Not sure why continuous-integration is show orange. It looks done when you inspect.

@oxinabox Can we pull this please?

**Comment by oxinabox** [comment]
Travis has been weird about that. Thanks for this

**Pull request merged**
