### PR TITLE
Add zenodo DOI badge

### LINKED ISSUE #70: Citation?
I'm using JLSO.jl for one of my research papers and I wish to cite this package. Is there a bibtex file or should I just make one myself?

### PR DESCRIPTION
**Pull request by rofinn**
Closes #70

### CODE REVIEW

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
Should also add a `Citation.bib` file.

**Comment by oxinabox** [comment]
Should also add a `Citation.bib` file.

**Comment by oxinabox** [comment]
Should also add a Citation.bib file

**Comment by rofinn** [comment]
Should probably fix up the author list first.

**Comment by rofinn** [comment]
Also, will we need to update the Citation.bib for every release?

**Comment by oxinabox** [comment]
> Also, will we need to update the Citation.bib for every release?

No. Just once really, unless enough changes are made that the author list needs to change.
We should just not include the version of the package in the Citation.bib
And once we have a JOSS paper it can just be a citation for that paper

**Pull request merged**
