### PR TITLE
Fix String -> Symbol type assertion

### PR DESCRIPTION
**Pull request by haampie**
Fixes the other #47 issue

### CODE REVIEW

**Comment by nickrobinson251** [comment]
Thanks :) Please can you add tests, and then bump the patch version?

**Comment by haampie** [comment]
ERROR: LoadError: LoadError: InitError: Unable to automatically install 'OpenBLAS' from '/Users/travis/.julia/packages/OpenBLAS_jll/cl4ZS/Artifacts.toml' seems unrelated?

**Comment by haampie** [comment]
Should we rerun travis?

**Comment by oxinabox** [comment]
rerunning

**Comment by haampie** [comment]
Much better!

**Comment by oxinabox** [comment]
Thanks! LGTM

**Comment by nickrobinson251** [comment]
Thanks!

**Pull request merged**
